environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: ""
platform:
  - x86
  - x64
cache:
- node_modules
- "%LOCALAPPDATA%\\Yarn"
install:
- ps: Install-Product node $env:nodejs_version $env:platform
- yarn install
test_script:
- yarn test
build: off
