engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: .eslintrc.yml
  fixme:
    enabled: true
  # Waiting on https://github.com/nodesecurity/nsp/pull/142 to support yarn.lock
  nodesecurity:
    enabled: false
  markdownlint:
    enabled: true
    checks:
      MD024:
        enabled: false
      MD033:
        enabled: false
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.md"
  - "**.sh"
exclude_paths:
- .vscode
- example
- lib
- test
