/** Declaration file generated by dts-gen */

export = Kitsu;

declare class Kitsu {
    constructor(...args: any[]);

    delete(...args: any[]): void;

    get(...args: any[]): void;

    patch(...args: any[]): void;

    post(...args: any[]): void;

    self(...args: any[]): void;

}

declare namespace Kitsu {
    namespace prototype {
        function get(...args: any[]): void;

        function patch(...args: any[]): void;

        function post(...args: any[]): void;

        function self(...args: any[]): void;

    }

}

