/** Declaration file generated by dts-gen */

export function camel(s: any): void;

export function deattribute(...args: any[]): any;

export function deserialise(...args: any[]): any;

export function error(E: any): void;

export function filterIncludes(...args: any[]): any;

export function kebab(s: any): void;

export function linkRelationships(...args: any[]): any;

export function query(params: any, ...args: any[]): any;

export function serialise(...args: any[]): any;

export function snake(s: any): void;

export namespace deattribute {
    const prototype: {
    };

}

export namespace deserialise {
    const prototype: {
    };

}

export namespace error {
    const prototype: {
    };

}

export namespace filterIncludes {
    const prototype: {
    };

}

export namespace linkRelationships {
    const prototype: {
    };

}

export namespace query {
    const prototype: {
    };

}

export namespace serialise {
    const prototype: {
    };

}

