name: Yarn
on: [pull_request]
jobs:
  yarn_lock_changes:
    name: Lock File Changes
    runs-on: ubuntu-latest
    # Permission overwrite is required for Dependabot PRs
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Digest Lock File
        uses: Simek/yarn-lock-changes@4cbe0acde4287304e36db1e684e015339a1d39f6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          collapsibleThreshold: 25
          failOnDowngrade: false
          path: yarn.lock
          updateComment: true
